# Grid Search Configuration
# Edit this file to customize the grid search parameters

# Seeds for reproducibility (list of integers)
seeds: [6,7,8,9,10]

noise_variance: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1 ] 

# Optimizers to test
optimizers: ["Adam"]

# Base experiment config file (relative to project root)
base_config: "configs/config_new.yaml"


 